- src/components/Story/Story.jsx
- src/components/Story/StoryContainer.jsx
- src/components/Story/StoryList.jsx
- src/components/Story/StoryListContainer.jsx
> Fix : "Story에 Navibar 반영"

- src/components/Auth/FindID.jsx
- src/components/Auth/FindIDnPW.jsx
- src/components/Auth/FindPW.jsx
- src/components/Auth/Login.jsx
> Design : "아이디/비밀번호 찾기 UI 구현"

- src/pages/Auth.jsx
> Add : "FindIDnPW route 추가"

- src/components/Auth/FindIDnPW.jsx
- src/components/Auth/FindPW.jsx
- src/functions/Auth/FindPw.js
Feat : "아이디, 비밀번호 찾기 서버 연결", Design : "아이디, 비밀번호 찾기 탭 중앙정렬"
> Feat : "아이디, 비밀번호 찾기 서버 연결", Design : "아이디, 비밀번호 찾기 탭 중앙정렬"

- src/components/Auth/EmailExist.js
- src/components/Auth/EmailNotExist.js
- src/components/Auth/FindIDnPW.jsx
- src/functions/Auth/FindId.js
- src/functions/Auth/FindPw.js
아이디 및 비밀번호 찾기에서 아이디가 DB에 존재하는지 확인 후, 각 상황에 맞게 페이지 라우팅 완료.
> Feat : "ID/PW 찾기 유효성 확인 및 각 페이지로 라우팅 구현"

- src/components/Auth/FindIDnPW.jsx
- src/components/Auth/FindIDnPW/EmailNotExist.jsx
- src/components/Auth/FindIDnPW/FindID.jsx
- src/components/Auth/FindIDnPW/FindPW.jsx
- src/components/Auth/FindIDnPW/SetNewPassword.jsx
- src/functions/Auth/FindId.js
- src/functions/Auth/FindPw.js
- src/pages/Auth.jsx
비밀번호 변경시 링크로 바로 이동해올 수 있게 라우팅 전반적으로 Auth page에서 라우팅 방식으로 바꿨음
그리고 비밀번호 찾기 부분도 추가해서 일단 만들어놨는데 그래도 문제가 남아있음
Issue에다가 정리할 예정
> Auth Routing Set and FindPW handle

- src/App.jsx
- src/components/Story/StoryListPage.jsx
- src/components/Story/components/SearchBar.js
- src/components/Story/components/StoryList.js
- src/components/common/Navibar.jsx
- src/pages/Story.jsx
스토리 페이지를 검색창 및 스토리 목록 컴포넌트로 분리함.
> Refactor : "스토리 페이지 구조 변경"

- src/components/Story/StoryListPage.jsx
- src/components/Story/components/Pagination.jsx
- src/components/Story/components/StoryList.js
> Feat : "스토리 list 페이지 pagination 구현"

- src/components/Story/components/Pagination.jsx
- src/components/Story/data.json
> Add : "json data 추가"

- src/pages/Home.jsx
> Fix : "home page 반응형 웹으로 수정"

- src/pages/Home.jsx
> Fix : "home page 반응형 웹으로 재수정"

- src/components/SpotMap/SpotList.jsx
- src/components/SpotMap/SpotList/ItemCard.js
- src/pages/SpotMap.jsx
Add : "left store list api url"
> Add : "left store list api url"

- src/components/Auth/Login.jsx
- src/components/SpotMap/SpotList/ItemCard.js
- src/components/common/Loading.js
- src/components/common/Navibar.jsx
> Fix : "setCookie, getCookie"

- src/components/SpotMap/SpotDetail.jsx
- src/components/SpotMap/SpotDetail/DetailCard.js
- src/components/SpotMap/SpotList/ItemCard.js
- src/components/common/Navibar.jsx
1. Add : "remove Cookie"
2. Feat : "detail modal"
> Add : "remove Cookie", Feat : "detail modal"

- src/components/SpotMap/SpotDetail.jsx
- src/components/SpotMap/SpotDetail/DetailCard.js
- src/components/SpotMap/SpotList/ItemCard.js
- src/components/common/Navibar.jsx
1. Feat : "detail page UI and api url"
2. Add : "like button"
> Feat : "detail page UI and api url", Add : "like button"

- src/components/SpotMap/SpotDetail.jsx
- src/components/SpotMap/SpotDetail/DetailCard.js
- src/components/mypage/Mypage.jsx
- src/components/mypage/myplace/Myplace.jsx
- src/pages/MyPage.jsx
1. #70 [main] Feat : "mypage tab list"
2. #71 Fix "map detail page id"
3. #72 Feat : "my place list api url"
> #70 [main] Feat : "mypage tab list", #71 [main] Fix "map detail page id", #72 [main] Feat : "my place list api url"

- src/components/Auth/Login.jsx
- src/components/common/Navibar.jsx
- src/components/mypage/Mypage.jsx
- src/pages/Home.jsx
- src/pages/MyPage.jsx
#74 Feat : "login 유지 및 mypage 접근 여부"
> #74 Feat : "login 유지 및 mypage 접근 여부"

- src/components/mypage/myplace/ItemCard.jsx
- src/components/mypage/myplace/Myplace.jsx
1. grid width 유지하도록 수정.
2. item card component 분리.
> #78 Fix : "grid width and like component"

- src/pages/SpotMap.jsx
> #80 Feat : "No Auth"

- src/App.jsx
- src/components/Auth/module/LeftAlignedLink.jsx
- src/components/Auth/module/ProfileButton.jsx
- src/components/Auth/module/index.js
- src/components/Story/components/StoryList.js
- src/components/mypage/Mypage.jsx
- src/components/mypage/myInfo/ChangeForm.jsx
- src/components/mypage/myInfo/InfoForm.jsx
- src/components/mypage/myplace/ItemCard.jsx
- src/components/mypage/myplace/Myplace.jsx
1. #82 Fix : "error"
2. #83 Feat : "mypage UI, api URL , change form", 
3. #84 Fix : "like_place api request"
> #82 Fix : "error", #83 Feat : "mypage UI, api URL , change form", #84 Fix : "like_place api request"

- src/components/SpotMap/Map.jsx
#86 Add : "current position api url"
> #86 Add : "current position api url"

- src/components/SpotMap/SpotList.jsx
- src/components/mypage/myplace/Myplace.jsx
- src/pages/SpotMap.jsx
#84 Fix : "place_list pagination"
> #84 Fix : "place_list pagination"

- src/components/SpotMap/SpotDetail.jsx
- src/components/SpotMap/SpotDetail/DetailCard.js
- src/components/mypage/myplace/Myplace.jsx
1. #84 Feat : "pagination api url"
2. #95 Add : "toggle button"
> #84 Feat : "pagination api url", #95 Add : "toggle button"

- src/components/SpotMap/SpotList.jsx
- src/components/mypage/myplace/Myplace.jsx
#84 Fix : "pagination api url"
> #84 Fix : "pagination api url"

- src/components/SpotMap/SpotList.jsx
- src/components/SpotMap/SpotList/ItemCard.js
- src/components/SpotMap/SpotList/SearchBar.js
- src/components/Story/components/StoryList.js
- src/components/common/Pagination.jsx
- src/components/mypage/Mypage.jsx
- src/components/mypage/myInfo/ChangeForm.jsx
- src/components/mypage/myInfo/InfoForm.jsx
- src/components/mypage/myInfo/SendFeedback.jsx
- src/components/mypage/myplace/Myplace.jsx
1. #92 Feat : "story list api url"
2. #98 Add : "send feedback UI"
3. #99 Feat : "search"
> #92 Feat : "story list api url", #98 Add : "send feedback UI", #99 Feat : "search"

- src/components/SpotMap/SpotList/ItemCard.js
- src/components/Story/components/ItemCard.jsx
- src/components/Story/components/StoryDetailBox.jsx
- src/components/Story/components/StoryList.js
- src/components/mypage/Mypage.jsx
- src/components/mypage/myplace/Myplace.jsx
- src/components/mypage/mystory/ItemCard.jsx
- src/components/mypage/mystory/Mystory.jsx
1. #92 Feat : "story api url"
2. #92 Feat : "story detail api url"
3. #101 Feat : "like story api url"
> #92 Feat : "story api url", #92 Feat : "story detail api url", #101 Feat : "like story api url"

- src/components/Story/components/StoryList.js
> #99 Add : "no data UI"

- src/components/mypage/mystory/ItemCard.jsx
- src/components/mypage/mystory/Mystory.jsx
> #101 Feat : "like story UI"

- src/components/mypage/myInfo/ChangeForm.jsx
- src/components/mypage/myInfo/InfoForm.jsx
#107 Feat : "edit profile image"
> #107 Feat : "edit profile image"

- src/components/SpotMap/SpotList/ItemCard.js
- src/components/Story/components/ItemCard.jsx
- src/components/Story/components/StoryDetailBox.jsx
- src/components/mypage/mystory/ItemCard.jsx
> #110 Feat : "close modal"

- src/components/SpotMap/SpotList.jsx
- src/pages/SpotMap.jsx
#112 Fix : "current location api url"
> #112 Fix : "current location api url"

- src/components/SpotMap/Map.jsx
- src/components/SpotMap/SpotDetail/DetailCard.js
- src/components/SpotMap/SpotList.jsx
- src/pages/SpotMap.jsx
1. #112 Fix : "map marker api url"
2. #114 Feat : "map marker click event modal"
> #112 Fix : "map marker api url", #114 Feat : "map marker click event modal"

- src/components/mypage/mystory/ItemCard.jsx
> #116 Feat "my story link"

- src/components/common/Loading.js
- src/components/mypage/myInfo/ChangeForm.jsx
> Fix : "loading component UI"

- src/components/Auth/Register.jsx
- src/components/Auth/module/SelectWithLabel.jsx
#119 Rename : "birthdate field"
> #119 Rename : "birthdate field"

- src/App.jsx
- src/components/SpotMap/Map.jsx
- src/components/Story/components/StoryDetailBox.jsx
- src/components/common/Loading.js
- src/index.css
- src/index.js
1. #121 Fix : "story html font style"
2. #88 Fix : "marker UI"
> #121 Fix : "story html font style", #88 Fix : "marker UI"

- src/components/Story/StoryListPage.jsx
> #84 Fix : "pagination"

- src/components/Story/StoryListPage.jsx
> #124 Feat : "story filter"

- src/components/Auth/FindIDnPW/SetNewPassword.jsx
- src/components/SpotMap/Map.jsx
- src/functions/Auth/ChangePw.js
> #129 Feat : "change pw"

- src/components/SpotMap/SpotDetail/DetailCard.js
- src/components/common/Navibar.jsx
- src/functions/common/PageRedirection.js
- src/pages/Home.jsx
1. #131 Rename : "MY PICK"
2. Add : "min-width"
> #131 Rename : "MY PICK", Add : "min-width"

- src/components/SpotMap/SpotDetail/DetailCard.js
- src/components/Story/components/StoryDetailBox.jsx
Fix : "btn UI, hide go to map btn"
> Fix : "btn UI, hide go to map btn"

- src/components/SpotMap/Map.jsx
> Fix : "map marker api url"

- src/components/Admin/Common.js
- src/components/Admin/StoryFormPage.jsx
> #140 Feat: "apply changed rep_pic API and add places select box"

- src/App.jsx
- src/components/Admin/PlaceFormPage.jsx
- src/components/Admin/components/DetailList.jsx
- src/components/SpotMap/SpotDetail.jsx
- src/components/mypage/myInfo/ChangeForm.jsx
> main : "create place admin page"

- src/components/Auth/Login.jsx
- src/components/mypage/myplace/Myplace.jsx
- src/functions/Auth/TryLogin.js
> #147 Fix : "response format"

- src/components/SpotMap/Map.jsx
- src/components/SpotMap/SpotDetail/DetailCard.js
- src/components/SpotMap/SpotList.jsx
- src/components/SpotMap/SpotList/ItemCard.js
- src/components/Story/StoryListPage.jsx
- src/components/Story/components/ItemCard.jsx
- src/components/Story/components/StoryDetailBox.jsx
- src/components/common/Navibar.jsx
- src/components/mypage/myInfo/ChangeForm.jsx
- src/components/mypage/myInfo/InfoForm.jsx
- src/components/mypage/myInfo/SendFeedback.jsx
- src/components/mypage/myplace/ItemCard.jsx
- src/components/mypage/myplace/Myplace.jsx
- src/components/mypage/mystory/ItemCard.jsx
- src/components/mypage/mystory/Mystory.jsx
- src/pages/SpotMap.jsx
> #151 Feat : "manage token"

- src/components/Auth/Login.jsx
#149 Add : "login fail alert & enter submit"
> #149 Add : "login fail alert & enter submit"

- src/components/SpotMap/Map.jsx
- src/components/SpotMap/Map_Container.jsx
- src/components/SpotMap/SpotList.jsx
- src/components/mypage/myInfo/ChangeForm.jsx
- src/pages/SpotMap.jsx
marker 20개 보이기 설정
email readonly
nickname 변경 동기화
> main : Bugfix/171

- src/components/SpotMap/DataContainer.jsx
- src/components/SpotMap/Map.jsx
> #194 feat : search here applied

- src/components/SpotMap/DataContainer.jsx
- src/components/SpotMap/Map.jsx
> #216 feat : map zoom slider applied & set position

- src/components/SpotMap/DataContainer.jsx
> #245 feat : category selected style change

- src/components/mypick/myplace/Myplace.jsx
- src/components/mypick/mystory/Mystory.jsx
> #272 feat : My Pick Category filter apply

- src/components/SpotMap/Map.jsx
> #283 feat : Improve marker's position accuracy

- src/components/common/Navibar.jsx
> #290 fix : fix redirect error when logged out in MyPick/MyPage

- package.json
> #285 feat : build  GENERATE_SOURCEMAP=false

- package.json
> #293 chore : "run sitemap creation script before build"

- src/components/mypage/myInfo/ChangeForm.jsx
- src/functions/common/Request.js
> #290 fix : alert for overlapped nickname when changing nickname

- public/index.html
> #331 chore : introduce google analytics

- src/pages/Home.jsx
> feat : redirect to map/story/mypick from home

- README.md
- public/index.html
- src/pages/Home.jsx
> chore : correct SASM official full name

- src/components/Story/components/Comment.jsx
- src/components/Story/components/WriteComment.jsx
BE 리팩토링 과정에서 수정한 story comments url 과 동일하게 FE도 수정했습니다.
> #367 feat: 'modify story comments urls'

- src/components/Community/Comments/Comment.jsx
- src/components/Community/Comments/UpdateComment.jsx
- src/components/Community/CommunityDetail.jsx
- src/components/Story/components/Comment.jsx
- src/components/Story/components/WriteComment.jsx
> #387 feat:Community comment pagination show update

- src/App.jsx
- src/components/SpotMap/SpotList/ItemCard.js
- src/components/common/Pagination.jsx
**목적**
1. #293 Feat : add address numbering : SEO 개선을 위해 각각 url 달아주기 ( 모든 장소 및 스토리 url로 접근 가능하도록 하도록 )
2. #293 button to Link : SEO 개선을 위해 button -> Link 로 변경
**변경 파일 3가지**
1. src/_App.jsx_
2. src/components/SpotMap/SpotList/_ItemCard.js_
3. src/components/common/_Pagination.jsx_
**변경 파일 변경점**
1. App.jsx 에 <Route path="/map/:id" element={<SpotMap />} /> 추가
2. ItemCard.js 에 div와 ImgBox 를 각각 TitleLink 와 ImgLink 로 변경,
그 후 TitleLink to={`/map/${placeData.id}`} 를 추가해주어 모달창에 각각의 url 배정
코멘트에 따라 Link가 placeData.place_name에만 적용. LikeButton이 작동되지 않는 이슈 방지
3. Pagination.jsx 에 styled.button`을 styled(Link)로 변경
**추가사항**
포크를 새로 하는 바람에 코멘트와 수정요청이 삭제되었습니다.
package.json, package-lock.json  커밋 파일에서 삭제
및 코멘트 사항 수정했습니다.
> #293 Feat : add address numbering, button to Link

- src/components/Story/StoryListPage.jsx
- src/components/Story/components/ItemCard.jsx
- src/components/Story/components/StoryDetailBox.jsx
- storylike 반환값  true/false로 수정
- 최신순/오래된 순 필드값을 order에서 latest로 수정
> #381 refactor: refactor StoryList

- src/components/Community/CommunityList.jsx
> #400 fix : Community hastag list query change

- package-lock.json
- package.json
- src/App.jsx
- src/components/Community/CommunityDetail.jsx
- src/components/Community/CommunityList.jsx
- src/components/SpotMap/DataContainer.jsx
- src/components/SpotMap/SpotList/ItemCard.js
- src/components/SpotMap/SpotList/ItemCard.jsx
- src/components/Story/StoryListPage.jsx
- src/components/Story/components/StoryDetailBox.jsx
- src/components/common/Pagination.jsx
- src/components/mypick/Mypick.jsx
- src/components/mypick/myplace/Myplace.jsx
- src/components/mypick/mystory/Mystory.jsx
- src/functions/common/PageRedirection.js
- src/pages/MyPick.jsx
- src/pages/SpotCommunity.jsx
**목적**
1. sdp-tech#293 Feat : path to queryparameter : SEO 개선을 위해 url주소에 queryparameter를 적용했습니다.
**변경 파일**
1. package-lock.json
2. package.json
3. src/App.jsx
4. src/components/Community/CommunityDetail.jsx
5. src/components/Community/CommunityList.jsx
6. src/components/SpotMap/DataContainer.jsx
7. src/components/SpotMap/SpotList/ItemCard.jsx
8. src/components/Story/StoryListPage.jsx
9. src/components/Story/components/StoryDetailBox.jsx
10. src/components/common/Pagination.jsx
11. src/components/mypick/Mypick.jsx
12. src/components/mypick/myplace/Myplace.jsx
13. src/components/mypick/mystory/Mystory.jsx
14. src/functions/common/PageRedirection.js
15. src/pages/MyPick.jsx
16. src/pages/SpotCommunity.jsx
**변경 파일 변경점**
1.  page 변수를 qs라이브러리를 이용해 query.page로 변경했습니다.
2. path 방식의 url을 …
> sdp-tech#293 Feat : path to queryparameter

- src/components/Admin/StoryFormPage.jsx
Should be merged after https://github.com/sdp-tech/SASM_BE/pull/377
> #416 fix : change request field name in sdp-admin CreateCruation

- src/components/Admin/StoryFormPage.jsx
> Revert "#416 fix : change request field name in sdp-admin CreateCruation"

- src/components/Admin/StoryFormPage.jsx
Should be merged after [sdp-tech/SASM_BE#377](https://github.com/sdp-tech/SASM_BE/pull/377)
> #416 fix : change request field name in sdp-admin CreateStory

- src/components/Curation/components/CurationDetailBox.jsx
- src/components/Story/components/StoryDetailBox.jsx
> sdp-tech#469 feat : activate delete and button style change

- src/components/Admin/PlaceFormPage.jsx
- src/components/Admin/components/DetailList.jsx
- src/components/SpotMap/SpotDetail.jsx
- src/components/SpotMap/SpotDetail/DetailCard.jsx
**주요사항**
sns 기능 주석처리,  추후 있을 리펙토링 작업 시 활성화 여부 결정
Closes #471
> sdp-tech#471 refactor : sdp_api_change

- src/components/Story/StoryListPage.jsx
- src/components/Story/components/ItemCard.jsx
- src/components/Story/components/StoryDetailBox.jsx
- src/components/Story/components/StoryList.jsx
- src/pages/StoryDetail.jsx
페이지네이션 fixed
스토리 박스에  hover: scale 추가
반응형 업데이트
storyDetailPage 수정하기 버튼 오른쪽 하단 고정
> sdp-tech#476 design : story_ui_change

- src/pages/Home.jsx
> sdp-tech#476 design : home_ui_change

- src/components/SpotMap/DataContainer.jsx
- src/components/SpotMap/SpotList.jsx
- src/components/SpotMap/SpotList/ItemCard.jsx
- src/components/common/Category.jsx
> sdp-tech#476 design : map_ui_change

- src/components/Admin/components/AdminButton.jsx
- src/components/Auth/FindIDnPW/ChangePassword.jsx
- src/components/mypage/myInfo/ChangeForm.jsx
- src/components/mypage/myInfo/FollowerList.jsx
- src/components/mypage/myInfo/FollowingList.jsx
- src/components/mypage/myInfo/InfoForm.jsx
mypage는 70% 작업 완료, 추후 작업 예정 (의견 보내기 페이지, mypage 빈 곳 활용 등)
> sdp-tech#476 design : mypage_ui_change

- src/components/Auth/module/GoogleRedirect.jsx
- src/components/Auth/module/KakaoRedirect.jsx
- src/components/Auth/module/NaverRedirect.jsx
- src/functions/Auth/TrySocialLogin.js
> sdp-tech#483 fix : social login fix

- src/components/Admin/CurationFormPage.jsx
- src/components/Admin/FormModals/StoryListModal.jsx
curation admin 알림창 추가, 버튼 디자인 추가, 모달창 디자인 추가
모달 디자인 디테일 작업 필요
> sdp-tech#476 design : curation_modal_style

- src/components/Admin/CurationFormPage.jsx
- src/components/Admin/FormModals/StoryListModal.jsx
> sdp-tech#476 design : curation modal style change

- src/components/Curation/CurationListPage.jsx
- src/components/Curation/components/CurationDetailBox.jsx
- src/components/Curation/components/CurationList.jsx
- src/components/Curation/components/ItemCard.jsx
- src/components/common/Navibar.jsx
> sdp-tech#476 design : curation_ui_change

- src/components/Admin/CurationFormPage.jsx
- src/components/Admin/FormModals/StoryListModal.jsx
- src/functions/common/AlertMessage.js
message 함수 추가 및 curation form에 적용
> sdp-tech#476 design : curation form alert message

- src/components/mypage/myInfo/ChangeForm.jsx
> sdp-tech#490 fix : nickname change

- src/App.jsx
- src/functions/common/ScrollRestoration.js
> sdp-tech#492 fix : scroll restoration

- src/components/Community/Comments/Comment.jsx
- src/components/Community/CommunityDetail.jsx
- src/components/Community/CommunityList.jsx
- src/components/Curation/components/CurationDetailBox.jsx
- src/components/Story/components/StoryDetailBox.jsx
- src/components/mypage/myInfo/FollowerList.jsx
- src/components/mypage/myInfo/FollowingList.jsx
- src/functions/common/OtherUserData.js
> sdp-tech#494 feat : other user profile

- src/components/mypage/myInfo/ChangeForm.jsx
- src/components/mypage/myInfo/InfoForm.jsx
changeform에서 사진 교체 시 적용된 거 안보이는 오류 수정 및 mypage 자기소개 기능추가 (성별 및 주소는 추가 고려 중)
> sdp-tech#497 feat : mypage introduction

- src/components/SpotMap/DataContainer.jsx
- src/components/SpotMap/Map.jsx
- src/components/mypage/myInfo/InfoForm.jsx
마이페이지 내 활동 내역 확인 가능 및 이동 가능. 맵으로 이동 기능도 완성했으나, 현재 맵에서 렌더링 오류가 생겨 주석처리해놓음
> sdp-tech#497 feat : mypage my history

- src/functions/common/OtherUserData.js
> sdp-tech#494 fix : no apply introduction

- src/components/Curation/components/CurationDetailBox.jsx
큐레이션 삭제 시 1페이지로 이동하되, writer의 isVerified 상태에 따라 usercuration 페이지 curation 페이지로 구분함
Close #502
> sdp-tech#502 fix : curation delete navigate

- src/components/SpotMap/SpotDetail/DetailCard.jsx
> sdp-tech#507 fix : map like fix

- src/components/mypage/myInfo/InfoForm.jsx
- src/functions/common/OtherUserData.js
안 만들어도 될 거 같았지만 없으면 허전할 거 같아서 마이페이지에서 내 프로필을 볼 수 있는 기능 추가
> sdp-tech#497 feat : my profile modal

- src/components/mypick/mycuration/MyCuration.jsx
- src/components/mypick/myplace/Myplace.jsx
- src/components/mypick/mystory/Mystory.jsx
1. mypick api  user에서 mypage로 api 변경
2. 검색 기능 활성화
3. 쿼리 파라미터로 url 부여
> sdp-tech#450 feat : mypage api change and searchbar implementation

- src/components/Community/CommunityList.jsx
- src/components/Curation/CurationListPage.jsx
- src/components/Curation/components/CurationMoreView.jsx
- src/components/Curation/components/CurationUserMoreView.jsx
- src/components/SpotMap/DataContainer.jsx
- src/components/Story/StoryListPage.jsx
1. 공백 값을 제거하는 코드 추가
2. communityListPage url에 쿼리 파라미터 부여
Closes #513
> sdp-tech#513 fix : search blank error

- src/components/Story/components/StoryDetailBox.jsx
- src/pages/StoryDetail.jsx
1. 글을 쓴 사람의 이메일과 사용자의 이메일을 비교해 일치하면 수정하기가 뜨도록, 아니면 뜨지 않도록 해 혼동 가능성을 줄임
Closes #515
> sdp-tech#515 fix : story update ui change

- src/App.jsx
- src/components/Admin/CurationFormPage.jsx
- src/components/Admin/FormModals/StoryListModal.jsx
- src/components/Admin/StoryFormPage.jsx
- src/components/Curation/components/CurationDetailBox.jsx
1. 큐레이션 수정 기능 추가 및 게시글 업로드 시 해당 게시물로 navigate 되는 기능 추가. 
2. ~~현재 수정 시 rep_pic이 없어 사진이 뜨지 않는데 api에서 해당 기능 추가되면 작업 예정~~ 수정완료
3. ~~스토리 및 큐레이션에서 수정 시, 각각 403 (forbidden), 400 (bad request) 에러가 남. 리뷰하면서 혹시 이상한 부분 체크 부탁~~ 수정완료
4. ~~2, 3과 같은 이유로 현재 큐레이션 수정하기 기능과 app의 route 부분 주석처리 해둠~~ 수정완료
> sdp-tech#509 feat : add curation update

- src/App.jsx
- src/components/Community/CommunityDetail.jsx
- src/components/Curation/components/CurationDetailBox.jsx
- src/components/Story/components/StoryDetailBox.jsx
- src/components/common/NotExistPage.jsx
존재하지 않는 페이지에 접근하려고 할 때 보여줄 페이지 작성
> sdp-tech#476 feat : not exist page

- src/components/Admin/CurationFormPage.jsx
- src/components/Admin/PlaceFormPage.jsx
- src/components/Admin/StoryFormPage.jsx
- src/components/common/NotExistPage.jsx
수정하기 페이지에서 존재하지 않는 곳으로 이동하면 존재하지 않는 페이지임을 알려주는 기능 추가
> sdp-tech#476 feat : add not exist page

- src/components/Admin/CurationFormPage.jsx
- src/components/Admin/StoryFormPage.jsx
- src/components/Curation/components/CurationList.jsx
- src/components/common/NotExistPage.jsx
다른 사람 글에 접근해 수정하려고 할 때 보여줄 페이지 생성
> sdp-tech#476 feat : add not authorization

- src/components/Curation/components/CurationDetailBox.jsx
- src/components/SpotMap/SpotDetail/UserReview.jsx
- src/components/SpotMap/SpotList/ItemCard.jsx
- src/components/Story/components/Comment.jsx
- src/components/Story/components/StoryDetailBox.jsx
- src/functions/common/OtherUserData.js
1. 댓글에서 타유저 프로필을 확인할 수 있게 함
2. 프로필 조회 기능이 있다는 것을 알려주기 위해 cursor: pointer 추가
3. 스토리 좋아요 개수 반환
4. map 좋아요 위치 수
> sdp-tech#494 feat : check otheruser profile at comment

- src/components/Community/CommunityDetail.jsx
- src/components/Community/CommunityList.jsx
1. 커뮤니티 게시물 좋아요를 누르면 작성날짜가 update되는 것 수정
2. 커뮤니티 디테일에서 좋아요 개수 반환
> sdp-tech#523 fix : change updated to created and add likecount

- src/components/Community/CommunityDetail.jsx
- src/pages/SpotCommunity.jsx
유효하지 않은 접근 시, 존재하지 않는 페이지임을 보여주는 예외 처리 추가
> sdp-tech#523 fix : community url exception handling

- src/components/SpotMap/DataContainer.jsx
- src/components/SpotMap/Map.jsx
> sdp-tech#476 fix : map rendering error

- src/functions/common/OtherUserData.js
1. 토큰 null로 반환되는 것 수정
2. 맵 리뷰 추가
> sdp-tech#494 feat : add other user map review

- src/assets/img/Map/MarkerbgActive.svg
- src/assets/img/Map/MarkerbgDefault.svg
- src/components/SpotMap/Map.jsx
- src/components/SpotMap/SpotList/ItemCard.jsx
1. 마커 이미지 변경 
2. ~~현재 아이템 카드에서 클릭 시 오류 발생. 머지 보류~~ 수정완료
3. 클릭 시 z-index 적용 안되는 부분 수정
> sdp-tech#476 : feat : add place name at marker and marker ui change

- src/components/SpotMap/Map.jsx
1. 이름이 11자가 넘는 곳은 ...으로 생략하였음
2. 가게 이름 및 카테고리 정렬
3. 현재 위치에서 검색 hover 효과 추가
> sdp-tech#476 feat : map marker update

- src/components/SpotMap/DataContainer.jsx
- src/components/SpotMap/Map.jsx
- src/components/SpotMap/SpotDetail.jsx
- src/components/SpotMap/SpotDetail/DetailCard.jsx
- src/components/SpotMap/SpotList/ItemCard.jsx
1. checklist에서 선택할 시 모두 클릭 활성화되는 것 수정
2. checklist 누를 시 searchparams 추가
3. detailcard에 영업시간 수정, 크기 안맞는 것 수정
> sdp-tech#476 fix : map checklist and detailcard style change

- src/components/Story/StoryListPage.jsx
- src/components/Story/components/ItemCard.jsx
- src/components/Story/components/StoryList.jsx
1. 스토리 리스트 반응형 수정
2. 주석처리 된 코드 몇 개 제거
> sdp-tech#476 : fix : storylist responsive design

- src/components/Auth/FindIDnPW.jsx
- src/components/Auth/Login.jsx
- src/components/Auth/Register.jsx
- src/components/mypage/myInfo/InfoForm.jsx
- src/functions/common/Request.js
1. 가입 페이지 및 마이페이지에서 생년월일 삭제
2. 로그인 후에 auth 관련 접속 시 잘못된 접속임을 알림
3. request에서 console.log 삭제
> sdp-tech 497 fix : delete birth date and add not exist page

- src/components/Curation/components/CurationDetailBox.jsx
1. curation에 나열된 스토리에 각각 go to map 부여
> sdp-tech#476 feat : add curation go to map

- src/functions/common/OtherUserData.js
프로필에서 댓글보기 이동 시, 댓글 페이지로 navigate되도록 수정
> sdp-tech#494 fix : profile to review

- src/components/Community/CommunityUpload.jsx
커뮤니티 게시글을 올린 후 해당 게시글로 navigate 되도록 수정
> sdp-tech#523 fix : navigate after posting

- src/components/SpotMap/DataContainer.jsx
카테고리를 눌렀을 때 페이지 1로 초기화 되지 않는 부분 수정
> sdp-tech#476 fix : checkedList page error

- src/components/SpotMap/DataContainer.jsx
- src/components/common/Pagination.jsx
첫 페이지 마지막 페이지 버튼 추가 및 글자 크기 변경
> sdp-tech#476 feat : pagination first page and last page button

- public/index.html
- src/components/SpotMap/DataContainer.jsx
1. map에 url 적용했던 게 중복되는 현상 발생해서 삭제
2. index.html에서 ko로 수정, 구글에서 한국어로 번역기 돌리는 창 안볼 수 있음
> sdp-tech#476 fix : map querystring

- src/components/Auth/module/GoogleRedirect.jsx
- src/components/Auth/module/KakaoRedirect.jsx
- src/components/Auth/module/NaverRedirect.jsx
소셜 로그인 시 글 삭제가 안보이는 현상 확인, localStorage에 email 저장되지 않는 것 수정
> sdp-tech#476 fix : add social login email localStorage

- src/components/Community/CommunityList.jsx
- src/components/Curation/components/CurationMoreView.jsx
- src/components/Curation/components/CurationUserMoreView.jsx
- src/components/SpotMap/DataContainer.jsx
- src/components/Story/StoryListPage.jsx
- src/components/mypage/myInfo/FollowerList.jsx
- src/components/mypage/myInfo/FollowingList.jsx
- src/components/mypage/myInfo/InfoForm.jsx
- src/components/mypick/mycuration/MyCuration.jsx
- src/components/mypick/myplace/Myplace.jsx
- src/components/mypick/mystory/Mystory.jsx
- src/functions/common/PageRedirection.js
> sdp-tech#559 fix : queryparameter navigate error

- src/components/Community/CommunityList.jsx
- src/components/Curation/components/CurationMoreView.jsx
- src/components/Curation/components/CurationUserMoreView.jsx
- src/components/SpotMap/DataContainer.jsx
- src/components/Story/StoryListPage.jsx
- src/components/common/Pagination.jsx
- src/components/mypage/myInfo/FollowerList.jsx
- src/components/mypage/myInfo/FollowingList.jsx
- src/components/mypick/mycuration/MyCuration.jsx
- src/components/mypick/myplace/Myplace.jsx
- src/components/mypick/mystory/Mystory.jsx
> sdp-tech#559 fix : does not redirect to page one

- src/components/Community/CommunityList.jsx
- src/components/Curation/CurationListPage.jsx
- src/components/Curation/components/CurationMoreView.jsx
- src/components/Curation/components/CurationUserMoreView.jsx
- src/components/Story/StoryListPage.jsx
스토리, 큐레이션, 커뮤니티에 우선적용. 팔로잉 페이지나  마이페이지는 다른 작업 후 업데이트 예정
> sdp-tech#559 feat : go back data update story curation community

- src/components/mypage/myInfo/InfoForm.jsx
팔로우 페이지는 현상태로 두는 것이 좋을 것 같아 초기 queryparameter만 변경
> sdp-tech#559 fix : follow page first queryparameter

- src/components/mypage/myInfo/FollowerList.jsx
- src/components/mypage/myInfo/FollowingList.jsx
1. 팔로우 페이지에서 엔터키를 누를 시 마이페이지로 이동되는 현상 수정
2. 뒤로 가기 시 데이터 가져오기 추가
> sdp-tech#559 fix : follow page go back data

- src/components/Admin/CurationFormPage.jsx
- src/components/Curation/CurationListPage.jsx
> sdp-tech#476 fix : curation form search

- src/components/SpotMap/Map.jsx
- src/functions/Auth/TrySocialLogin.js
> sdp-tech#591 feat: change naver api key

- src/components/Community/Comments/Comment.jsx
- src/components/Community/CommunityDetail.jsx
> sdp-tech#476fix : community comment hover
